services:
  hammerdb:
    image: tpcorg/hammerdb:latest
    container_name: hammerdb_container
  postgres:
    image: postgres:17.6-trixie
    container_name: postgres_container
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres_container
      DB_NAME: postgres
      AUTH_TYPE: "scram-sha-256"
    ports:
      - "6432:6432"